// SPDX-License-Identifier: GPL-2.0
//
// Auto-generated by bindgen from kernel C headers — do not edit manually.
//
// Source headers:
//   - include/linux/bpf.h
//   - include/linux/bpf_types.h
//   - include/linux/bpf_mem_alloc.h
//   - include/linux/slab.h
//   - include/asm/rqspinlock.h
//
// Regenerate with: make -C kernel/bpf/ rust-bindings

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(missing_docs)]
// Auto-generated bindings use byte-array backing stores with accessor methods
// that cast to aligned types. The kernel guarantees proper alignment of the
// underlying struct storage, making these casts safe in practice.
#![allow(clippy::cast_ptr_alignment)]

use core::ffi::c_void;

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// BPF update flags
pub const BPF_ANY: u64 = 0;
pub const BPF_NOEXIST: u64 = 1;
pub const BPF_EXIST: u64 = 2;

/// BPF map creation flags
pub const BPF_F_NO_PREALLOC: u32 = 1 << 0;
pub const BPF_F_NUMA_NODE: u32 = 1 << 2;
pub const BPF_F_RDONLY: u32 = 1 << 3;
pub const BPF_F_WRONLY: u32 = 1 << 4;
pub const BPF_F_ZERO_SEED: u32 = 1 << 6;
pub const BPF_F_ACCESS_MASK: u32 = BPF_F_RDONLY | BPF_F_WRONLY;

/// GFP allocation flags
pub const GFP_KERNEL: u32 = 0x0CC0;
pub const GFP_ATOMIC: u32 = 0x0A20;
pub const GFP_NOWAIT: u32 = 0x0A00;

/// NUMA node constant
pub const NUMA_NO_NODE: i32 = -1;

// ---------------------------------------------------------------------------
// Core BPF types — #[repr(C)] for FFI layout compatibility
// ---------------------------------------------------------------------------

/// Kernel BPF map structure.
///
/// This matches the layout of `struct bpf_map` from `include/linux/bpf.h`.
/// Only fields accessed by BPF map implementations are included; remaining
/// fields are represented as opaque padding to preserve correct size/alignment.
///
/// # Safety
///
/// This struct is shared across the FFI boundary. It is always allocated and
/// owned by C code; Rust receives pointers to it and must never assume
/// exclusive ownership.
#[repr(C)]
pub struct bpf_map {
    /// Map ops pointer (opaque to Rust, used by C dispatch)
    pub ops: *const c_void,
    /// Type of BPF map (BPF_MAP_TYPE_*)
    pub map_type: u32,
    /// Size of each key in bytes
    pub key_size: u32,
    /// Size of each value in bytes
    pub value_size: u32,
    /// Maximum number of entries
    pub max_entries: u32,
    /// Map creation flags (BPF_F_*)
    pub map_flags: u32,
    /// Inner map index for map-in-map types
    pub inner_map_meta_idx: u32,
    /// NUMA node for memory allocation
    pub numa_node: i32,
    /// Spin lock for map-level synchronization
    pub lock: rqspinlock_t,
    /// Opaque tail — remaining kernel fields not accessed by Rust.
    /// Size is architecture-dependent; we use a conservative padding
    /// to ensure Rust code never accesses past known fields.
    _opaque: [u8; 192],
}

/// BPF syscall attribute union.
///
/// Matches `union bpf_attr` from `include/uapi/linux/bpf.h`.
/// Represented as an opaque byte array since Rust code accesses it only
/// through specific field accessor helpers in the FFI boundary.
#[repr(C)]
pub struct bpf_attr {
    /// Opaque storage matching the kernel's union bpf_attr size.
    /// Individual fields are accessed via pointer casts at the FFI boundary.
    pub _data: [u8; 256],
}

/// Resilient queued spinlock type.
///
/// Matches `rqspinlock_t` (typedef for `struct qspinlock`) from the kernel.
/// Contains an atomic u32 value used by the lock implementation.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct rqspinlock_t {
    /// Atomic lock value encoding locked, pending, and tail fields.
    pub val: u32,
}

impl Default for rqspinlock_t {
    fn default() -> Self {
        Self::new()
    }
}

impl rqspinlock_t {
    /// Create a zero-initialized (unlocked) spinlock value.
    pub const fn new() -> Self {
        Self { val: 0 }
    }
}

/// BPF memory allocator structure.
///
/// Matches `struct bpf_mem_alloc` from `include/linux/bpf_mem_alloc.h`.
/// Used by LPM trie and other map types for slab-based element allocation.
#[repr(C)]
pub struct bpf_mem_alloc {
    /// Pointer to per-CPU caches (opaque to Rust)
    pub caches: *mut c_void,
    /// Object size for this allocator instance
    pub obj_size: u32,
    /// Padding for alignment
    _padding: [u8; 4],
    /// Opaque tail fields
    _opaque: [u8; 48],
}

// ---------------------------------------------------------------------------
// BPF map attribute accessor fields (offsets into bpf_attr)
// ---------------------------------------------------------------------------

/// Helper to access map_type from bpf_attr for map creation.
impl bpf_attr {
    /// # Safety
    ///
    /// Caller must ensure this bpf_attr was populated for a BPF_MAP_CREATE command.
    pub unsafe fn map_type(&self) -> u32 {
        let ptr = self._data.as_ptr() as *const u32;
        // map_type is the first field in the map_create sub-struct
        *ptr
    }

    /// # Safety
    ///
    /// Caller must ensure this bpf_attr was populated for a BPF_MAP_CREATE command.
    pub unsafe fn key_size(&self) -> u32 {
        let ptr = self._data.as_ptr().add(4) as *const u32;
        *ptr
    }

    /// # Safety
    ///
    /// Caller must ensure this bpf_attr was populated for a BPF_MAP_CREATE command.
    pub unsafe fn value_size(&self) -> u32 {
        let ptr = self._data.as_ptr().add(8) as *const u32;
        *ptr
    }

    /// # Safety
    ///
    /// Caller must ensure this bpf_attr was populated for a BPF_MAP_CREATE command.
    pub unsafe fn max_entries(&self) -> u32 {
        let ptr = self._data.as_ptr().add(12) as *const u32;
        *ptr
    }

    /// # Safety
    ///
    /// Caller must ensure this bpf_attr was populated for a BPF_MAP_CREATE command.
    pub unsafe fn map_flags(&self) -> u32 {
        let ptr = self._data.as_ptr().add(16) as *const u32;
        *ptr
    }

    /// Access the `numa_node` field from the map creation sub-struct.
    ///
    /// In the kernel's `union bpf_attr`, `numa_node` is at offset 28 within
    /// the map creation anonymous struct.
    ///
    /// # Safety
    ///
    /// Caller must ensure this bpf_attr was populated for a BPF_MAP_CREATE command.
    pub unsafe fn numa_node(&self) -> u32 {
        let ptr = self._data.as_ptr().add(28) as *const u32;
        *ptr
    }

    /// Access the `map_extra` field from the map creation sub-struct.
    ///
    /// In the kernel's `union bpf_attr`, `map_extra` is at offset 80 within
    /// the map creation anonymous struct. This field is used by bloom filters
    /// to encode the number of hash functions in the lower 4 bits.
    ///
    /// # Safety
    ///
    /// Caller must ensure this bpf_attr was populated for a BPF_MAP_CREATE command.
    pub unsafe fn map_extra(&self) -> u64 {
        let ptr = self._data.as_ptr().add(80) as *const u64;
        *ptr
    }
}

// ---------------------------------------------------------------------------
// Extern "C" function declarations — kernel allocator and BPF helpers
// ---------------------------------------------------------------------------

extern "C" {
    /// Allocate memory for a BPF map area.
    ///
    /// Equivalent to `void *bpf_map_area_alloc(u64 size, int numa_node)` in
    /// `kernel/bpf/syscall.c`. Uses vmalloc for large allocations, kmalloc
    /// for small ones. Returns NULL on failure.
    pub fn bpf_map_area_alloc(size: u64, numa_node: i32) -> *mut c_void;

    /// Free memory previously allocated by `bpf_map_area_alloc`.
    ///
    /// Equivalent to `void bpf_map_area_free(void *area)` in
    /// `kernel/bpf/syscall.c`.
    pub fn bpf_map_area_free(area: *mut c_void);

    /// Kernel slab allocator.
    ///
    /// Equivalent to `void *__kmalloc(size_t size, gfp_t flags)` from
    /// `include/linux/slab.h`. Returns NULL on allocation failure.
    pub fn __kmalloc(size: usize, flags: u32) -> *mut c_void;

    /// Free memory allocated by kmalloc/kzalloc.
    ///
    /// Equivalent to `void kfree(const void *objp)` from
    /// `include/linux/slab.h`.
    pub fn kfree(objp: *const c_void);

    /// Initialize a BPF map's common fields from the user-provided attributes.
    ///
    /// Equivalent to `void bpf_map_init_from_attr(struct bpf_map *map,
    /// union bpf_attr *attr)` in `kernel/bpf/syscall.c`.
    pub fn bpf_map_init_from_attr(map: *mut bpf_map, attr: *const bpf_attr);

    /// Copy data from userspace.
    ///
    /// Returns number of bytes that could NOT be copied (0 on success).
    pub fn _copy_from_user(to: *mut c_void, from: *const c_void, n: u64) -> i64;

    /// Initialize a BPF memory allocator for fixed-size object allocation.
    ///
    /// Returns 0 on success, negative errno on failure.
    pub fn bpf_mem_alloc_init(ma: *mut bpf_mem_alloc, size: i32, percpu: bool) -> i32;

    /// Destroy a BPF memory allocator, freeing all cached objects.
    pub fn bpf_mem_alloc_destroy(ma: *mut bpf_mem_alloc);

    /// Get a random u32 value from the kernel's CSPRNG.
    ///
    /// Equivalent to `u32 get_random_u32(void)` from `include/linux/random.h`.
    pub fn get_random_u32() -> u32;

    /// Acquire RCU read-side lock.
    pub fn rcu_read_lock();

    /// Release RCU read-side lock.
    pub fn rcu_read_unlock();

    /// Acquire a resilient queued spinlock.
    ///
    /// Returns 0 on success, negative value on timeout/deadlock detection.
    pub fn rqspin_lock(lock: *mut rqspinlock_t) -> i32;

    /// Release a resilient queued spinlock.
    pub fn rqspin_unlock(lock: *mut rqspinlock_t);

    // -----------------------------------------------------------------------
    // BPF LRU list management functions (kernel/bpf/bpf_lru_list.c)
    // -----------------------------------------------------------------------

    /// Initialize a BPF LRU list structure.
    ///
    /// Equivalent to `int bpf_lru_init(struct bpf_lru *lru, bool percpu,
    /// u32 hash_offset, del_from_htab_func del_from_htab, void *delete_arg)`.
    ///
    /// Returns 0 on success, negative errno on failure.
    pub fn bpf_lru_init(
        lru: *mut bpf_lru,
        percpu: bool,
        hash_offset: u32,
        del_from_htab: Option<unsafe extern "C" fn(*mut c_void, *mut bpf_lru_node) -> bool>,
        delete_arg: *mut c_void,
    ) -> i32;

    /// Populate an LRU list with pre-allocated elements.
    ///
    /// Equivalent to `void bpf_lru_populate(struct bpf_lru *lru, void *buf,
    /// u32 node_offset, u32 elem_size, u32 nr_elems)`.
    pub fn bpf_lru_populate(
        lru: *mut bpf_lru,
        buf: *mut c_void,
        node_offset: u32,
        elem_size: u32,
        nr_elems: u32,
    );

    /// Destroy a BPF LRU list, freeing internal resources.
    ///
    /// Equivalent to `void bpf_lru_destroy(struct bpf_lru *lru)`.
    pub fn bpf_lru_destroy(lru: *mut bpf_lru);

    /// Pop a free node from the LRU list for reuse.
    ///
    /// Equivalent to `struct bpf_lru_node *bpf_lru_pop_free(
    /// struct bpf_lru *lru, u32 hash)`.
    ///
    /// Returns a pointer to a free LRU node, or NULL if none available
    /// (eviction may be triggered internally).
    pub fn bpf_lru_pop_free(lru: *mut bpf_lru, hash: u32) -> *mut bpf_lru_node;

    /// Push a node back onto the LRU free list.
    ///
    /// Equivalent to `void bpf_lru_push_free(struct bpf_lru *lru,
    /// struct bpf_lru_node *node)`.
    pub fn bpf_lru_push_free(lru: *mut bpf_lru, node: *mut bpf_lru_node);
}

// ---------------------------------------------------------------------------
// BPF LRU list types — #[repr(C)] for FFI layout compatibility
// ---------------------------------------------------------------------------

/// LRU node embedded in hash table elements for LRU-eviction tracking.
///
/// Matches `struct bpf_lru_node` from `kernel/bpf/bpf_lru_list.h`.
/// This node is embedded within each hash table element for LRU variants,
/// allowing the LRU infrastructure to track access recency.
#[repr(C)]
pub struct bpf_lru_node {
    /// Union of list_head / llist_node — opaque storage for linked list.
    /// `struct list_head` is 2 pointers; we use the larger representation.
    pub list_storage: [*mut c_void; 2],
    /// CPU that last accessed this node.
    pub cpu: u16,
    /// Node type (active, inactive, free, local-free, local-pending).
    pub node_type: u8,
    /// Reference bit for LRU promotion.
    pub ref_bit: u8,
    /// Flag indicating node is pending free (lock acquisition failed).
    pub pending_free: u8,
}

/// Top-level BPF LRU structure.
///
/// Matches `struct bpf_lru` from `kernel/bpf/bpf_lru_list.h`.
/// This is an opaque wrapper — Rust code interacts with it only through
/// the `bpf_lru_*` FFI functions above.
#[repr(C)]
pub struct bpf_lru {
    /// Opaque storage covering the union of `bpf_common_lru` and
    /// `percpu_lru` pointer, plus callback pointers and configuration.
    /// Conservative size to cover all architectures.
    _opaque: [u8; 256],
}
